[package]
name = "tagging_service"
version = "0.1.0"
edition = "2024"

[dependencies]
db_service = { path = "../db_service" }

tch = "0.19.0"
anyhow = "1.0.97"
image = { version = "0.25.5", features = [] }
rayon = "1.10.0"
