services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: photo-app
      POSTGRES_PASSWORD: d13s3l-ph0to
      POSTGRES_DB: photo_app_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "photo-app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
